/*
 * Quake Live retail Windows host -- Ghidra compatibility header
 *
 * Auto-generated by ExportQuakeLiveSteamSourceRecreation.py.
 * This header provides lightweight compatibility aliases for common Ghidra
 * placeholder types so the generated export reads more like conventional C++.
 */

#pragma once

#include <cstddef>
#include <cstdint>

#ifndef __cdecl
#define __cdecl
#endif

#ifndef __fastcall
#define __fastcall
#endif

#ifndef __stdcall
#define __stdcall
#endif

#ifndef __thiscall
#define __thiscall
#endif

using undefined = std::uint8_t;
using undefined1 = std::uint8_t;
using undefined2 = std::uint16_t;
using undefined4 = std::uint32_t;
using undefined8 = std::uint64_t;
using uchar = std::uint8_t;
using ushort = std::uint16_t;
using uint = std::uint32_t;
using ulong = std::uint32_t;
using longlong = std::int64_t;
using ulonglong = std::uint64_t;
using wchar16 = std::uint16_t;
using byte = std::uint8_t;
using float10 = long double;
using code = void;
