/*
===========================================================================
Copyright (C) 1999-2005 Id Software, Inc.

This file is part of Quake III Arena source code.

Quake III Arena source code is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

Quake III Arena source code is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Foobar; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
===========================================================================
*/
//
#ifndef __UI_PUBLIC_H__
#define __UI_PUBLIC_H__

#define UI_API_VERSION	7
#define UI_QL_API_VERSION	8

typedef void (QDECL *uiArenaNameCallback_t)( const char *name );

typedef struct {
	connstate_t		connState;
	int				connectPacketCount;
	int				clientNum;
	char			servername[MAX_STRING_CHARS];
	char			updateInfoString[MAX_STRING_CHARS];
	char			messageString[MAX_STRING_CHARS];
} uiClientState_t;

/*
==================================================================

legacy source / QVM ui syscall ABI

==================================================================
*/
typedef enum {
	UI_ERROR,
	UI_PRINT,
	UI_MILLISECONDS,
	UI_CVAR_SET,
	UI_CVAR_VARIABLEVALUE,
	UI_CVAR_VARIABLESTRINGBUFFER,
	UI_CVAR_SETVALUE,
	UI_CVAR_RESET,
	UI_CVAR_CREATE,
	UI_CVAR_INFOSTRINGBUFFER,
	UI_ARGC,
	UI_ARGV,
	UI_CMD_EXECUTETEXT,
	UI_FS_FOPENFILE,
	UI_FS_READ,
	UI_FS_WRITE,
	UI_FS_FCLOSEFILE,
	UI_FS_GETFILELIST,
	UI_R_REGISTERMODEL,
	UI_R_REGISTERSKIN,
	UI_R_REGISTERSHADERNOMIP,
	UI_R_CLEARSCENE,
	UI_R_ADDREFENTITYTOSCENE,
	UI_R_ADDPOLYTOSCENE,
	UI_R_ADDLIGHTTOSCENE,
	UI_R_RENDERSCENE,
	UI_R_SETCOLOR,
	UI_R_DRAWSTRETCHPIC,
	UI_UPDATESCREEN,
	UI_CM_LERPTAG,
	UI_CM_LOADMODEL,
	UI_S_REGISTERSOUND,
	UI_S_STARTLOCALSOUND,
	UI_KEY_KEYNUMTOSTRINGBUF,
	UI_KEY_GETBINDINGBUF,
	UI_KEY_SETBINDING,
	UI_KEY_ISDOWN,
	UI_KEY_GETOVERSTRIKEMODE,
	UI_KEY_SETOVERSTRIKEMODE,
	UI_KEY_CLEARSTATES,
	UI_KEY_GETCATCHER,
	UI_KEY_SETCATCHER,
	UI_GETCLIPBOARDDATA,
	UI_GETGLCONFIG,
	UI_GETCLIENTSTATE,
	UI_GETCONFIGSTRING,
	UI_LAN_GETPINGQUEUECOUNT,
	UI_LAN_CLEARPING,
	UI_LAN_GETPING,
	UI_LAN_GETPINGINFO,
	UI_CVAR_REGISTER,
	UI_CVAR_UPDATE,
	UI_MEMORY_REMAINING,
	UI_GET_CDKEY,
	UI_SET_CDKEY,
	UI_R_REGISTERFONT,
	UI_R_MODELBOUNDS,
	UI_PC_ADD_GLOBAL_DEFINE,
	UI_PC_LOAD_SOURCE,
	UI_PC_FREE_SOURCE,
	UI_PC_READ_TOKEN,
	UI_PC_SOURCE_FILE_AND_LINE,
	UI_S_STOPBACKGROUNDTRACK,
	UI_S_STARTBACKGROUNDTRACK,
	UI_REAL_TIME,
	UI_LAN_GETSERVERCOUNT,
	UI_LAN_GETSERVERADDRESSSTRING,
	UI_LAN_GETSERVERINFO,
	UI_LAN_MARKSERVERVISIBLE,
	UI_LAN_UPDATEVISIBLEPINGS,
	UI_LAN_RESETPINGS,
	UI_LAN_LOADCACHEDSERVERS,
	UI_LAN_SAVECACHEDSERVERS,
	UI_LAN_ADDSERVER,
	UI_LAN_REMOVESERVER,
	UI_CIN_PLAYCINEMATIC,
	UI_CIN_STOPCINEMATIC,
	UI_CIN_RUNCINEMATIC,
	UI_CIN_DRAWCINEMATIC,
	UI_CIN_SETEXTENTS,
	UI_R_REMAP_SHADER,
	UI_VERIFY_CDKEY,
	UI_LAN_SERVERSTATUS,
	UI_LAN_GETSERVERPING,
	UI_LAN_SERVERISVISIBLE,
	UI_LAN_COMPARESERVERS,
	// 1.32
	UI_FS_SEEK,
	UI_SET_PBCLSTATUS,
	UI_LAUNCHER_READSCREENSHOT,

	UI_MEMSET = 100,
	UI_MEMCPY,
	UI_STRNCPY,
	UI_SIN,
	UI_COS,
	UI_ATAN2,
	UI_SQRT,
	UI_FLOOR,
	UI_CEIL
} uiImport_t;

/*
==================================================================

recovered retail uix86.dll native import table

Keep this distinct from uiImport_t above. The source/QVM UI continues to use
the legacy syscall ABI, while the client-side native host bridge in cl_ui.c
uses these recovered slot numbers for retail DLL parity.

==================================================================
*/
#define UI_QL_NATIVE_IMPORT_COUNT	256

typedef enum {
	UI_QL_IMPORT_PRINT = 0,
	UI_QL_IMPORT_ERROR = 1,
	UI_QL_IMPORT_MILLISECONDS = 2,
	UI_QL_IMPORT_REAL_TIME = 3,
	UI_QL_IMPORT_CVAR_REGISTER = 4,
	UI_QL_IMPORT_CVAR_CREATE = 5,
	UI_QL_IMPORT_CVAR_UPDATE = 6,
	UI_QL_IMPORT_CVAR_SET = 7,
	UI_QL_IMPORT_CVAR_SET_VALUE = 8,
	UI_QL_IMPORT_CVAR_VARIABLE_STRING_BUFFER = 9,
	UI_QL_IMPORT_CVAR_VARIABLE_VALUE = 10,
	UI_QL_IMPORT_ARGC = 11,
	UI_QL_IMPORT_ARGV = 12,
	UI_QL_IMPORT_CMD_ARGS_BUFFER = 13,
	UI_QL_IMPORT_FS_FOPENFILE = 14,
	UI_QL_IMPORT_FS_READ = 15,
	UI_QL_IMPORT_FS_WRITE = 16,
	UI_QL_IMPORT_FS_FCLOSEFILE = 17,
	UI_QL_IMPORT_FS_SEEK = 18,
	UI_QL_IMPORT_FS_GETFILELIST = 19,
	UI_QL_IMPORT_CMD_EXECUTETEXT = 20,
	UI_QL_IMPORT_R_REGISTERMODEL = 21,
	UI_QL_IMPORT_R_REGISTERSKIN = 22,
	UI_QL_IMPORT_R_REGISTERSHADERNOMIP = 23,
	UI_QL_IMPORT_R_CLEARSCENE = 24,
	UI_QL_IMPORT_R_ADDREFENTITYTOSCENE = 25,
	UI_QL_IMPORT_R_ADDPOLYTOSCENE = 26,
	UI_QL_IMPORT_R_ADDLIGHTTOSCENE = 27,
	UI_QL_IMPORT_R_RENDERSCENE = 28,
	UI_QL_IMPORT_R_SETCOLOR = 29,
	UI_QL_IMPORT_R_DRAWSTRETCHPIC = 30,
	UI_QL_IMPORT_R_MODELBOUNDS = 31,
	UI_QL_IMPORT_UPDATESCREEN = 32,
	UI_QL_IMPORT_CM_LERPTAG = 33,
	UI_QL_IMPORT_S_STARTLOCALSOUND = 34,
	UI_QL_IMPORT_S_REGISTERSOUND = 35,
	UI_QL_IMPORT_KEY_KEYNUMTOSTRINGBUF = 36,
	UI_QL_IMPORT_KEY_GETBINDINGBUF = 37,
	UI_QL_IMPORT_KEY_SETBINDING = 38,
	UI_QL_IMPORT_KEY_ISDOWN = 39,
	UI_QL_IMPORT_KEY_GETOVERSTRIKEMODE = 40,
	UI_QL_IMPORT_KEY_SETOVERSTRIKEMODE = 41,
	UI_QL_IMPORT_KEY_CLEARSTATES = 42,
	UI_QL_IMPORT_KEY_GETCATCHER = 43,
	UI_QL_IMPORT_KEY_SETCATCHER = 44,
	UI_QL_IMPORT_GETCLIPBOARDDATA = 45,
	UI_QL_IMPORT_GETCLIENTSTATE = 46,
	UI_QL_IMPORT_GETGLCONFIG = 47,
	UI_QL_IMPORT_GETCONFIGSTRING = 48,
	UI_QL_IMPORT_LAN_GETSERVERCOUNT = 49,
	UI_QL_IMPORT_LAN_GETSERVERADDRESSSTRING = 50,
	UI_QL_IMPORT_LAN_GETSERVERINFO = 51,
	UI_QL_IMPORT_LAN_GETSERVERPING = 52,
	/*
	Retail keeps a four-slot LAN ping queue slab between GetServerPing and the
	cache helpers. The committed HLIL does not call these imports directly, but
	the surrounding browser order and the remaining legacy LAN helpers make this
	the narrowest stable fit.
	*/
	UI_QL_IMPORT_LAN_GETPINGQUEUECOUNT = 53,
	UI_QL_IMPORT_LAN_CLEARPING = 54,
	UI_QL_IMPORT_LAN_GETPING = 55,
	UI_QL_IMPORT_LAN_GETPINGINFO = 56,
	UI_QL_IMPORT_LAN_LOADCACHEDSERVERS = 57,
	UI_QL_IMPORT_LAN_SAVECACHEDSERVERS = 58,
	UI_QL_IMPORT_LAN_MARKSERVERVISIBLE = 59,
	UI_QL_IMPORT_LAN_SERVERISVISIBLE = 60,
	UI_QL_IMPORT_LAN_UPDATEVISIBLEPINGS = 61,
	UI_QL_IMPORT_LAN_ADDSERVER = 62,
	UI_QL_IMPORT_LAN_REMOVESERVER = 63,
	UI_QL_IMPORT_LAN_RESETPINGS = 64,
	UI_QL_IMPORT_LAN_SERVERSTATUS = 65,
	UI_QL_IMPORT_LAN_COMPARESERVERS = 66,
	/*
	Legacy UI syscall order and the preserved neighboring retail rows make
	MemoryRemaining the narrowest stable fit here.
	*/
	UI_QL_IMPORT_MEMORY_REMAINING = 67,
	UI_QL_IMPORT_GET_CDKEY = 68,
	UI_QL_IMPORT_SET_CDKEY = 69,
	UI_QL_IMPORT_R_REGISTERFONT = 70,
	UI_QL_IMPORT_S_STOPBACKGROUNDTRACK = 71,
	UI_QL_IMPORT_S_STARTBACKGROUNDTRACK = 72,
	UI_QL_IMPORT_CIN_PLAYCINEMATIC = 73,
	UI_QL_IMPORT_CIN_STOPCINEMATIC = 74,
	UI_QL_IMPORT_CIN_DRAWCINEMATIC = 75,
	UI_QL_IMPORT_CIN_RUNCINEMATIC = 76,
	UI_QL_IMPORT_CIN_SETEXTENTS = 77,
	/*
	Legacy UI syscall order and the surviving verify-cdkey adjacency leave
	R_RemapShader as the narrowest stable fit here.
	*/
	UI_QL_IMPORT_R_REMAP_SHADER = 78,
	UI_QL_IMPORT_VERIFY_CDKEY = 79,
	UI_QL_IMPORT_SETUP_ADVERT_CELL_SHADER = 80,
	UI_QL_IMPORT_REFRESH_ADVERT_CELL_SHADER = 81,
	UI_QL_IMPORT_INIT_ADVERTISEMENT_BRIDGE = 82,
	UI_QL_IMPORT_UNUSED_83 = 83,
	UI_QL_IMPORT_ACTIVATE_ADVERT = 84,
	UI_QL_IMPORT_UNUSED_85 = 85,
	UI_QL_IMPORT_SET_CURSOR_POS = 86,
	UI_QL_IMPORT_GET_CURSOR_POS = 87,
	UI_QL_IMPORT_PC_ADD_GLOBAL_DEFINE = 88,
	UI_QL_IMPORT_PC_LOAD_SOURCE = 89,
	UI_QL_IMPORT_PC_FREE_SOURCE = 90,
	UI_QL_IMPORT_PC_READ_TOKEN = 91,
	UI_QL_IMPORT_PC_SOURCE_FILE_AND_LINE = 92,
	UI_QL_IMPORT_IS_SUBSCRIBED_APP = 93,
	UI_QL_IMPORT_DRAW_SCALED_TEXT = 94,
	UI_QL_IMPORT_MEASURE_TEXT = 95,
	UI_QL_IMPORT_GET_ITEM_DOWNLOAD_INFO = 96,

	/*
	Source-side native bridge extensions beyond the recovered retail slab.
	These keep the current UI source functional when loaded through the native
	import table while the corresponding retail slots remain unmapped or absent.
	*/
	UI_QL_IMPORT_CVAR_RESET = 97,
	UI_QL_IMPORT_CVAR_INFOSTRINGBUFFER = 98,
	UI_QL_IMPORT_CM_LOADMODEL = 108,
	UI_QL_IMPORT_SET_PBCLSTATUS = 109,
	UI_QL_IMPORT_LAUNCHER_READSCREENSHOT = 110
} uiQlImport_t;

typedef enum {
	UIMENU_NONE,
	UIMENU_MAIN,
	UIMENU_INGAME,
	UIMENU_NEED_CD,
	UIMENU_BAD_CD_KEY,
	UIMENU_TEAM,
	UIMENU_POSTGAME
} uiMenuCommand_t;

#define SORT_HOST			0
#define SORT_MAP			1
#define SORT_CLIENTS		2
#define SORT_GAME			3
#define SORT_PING			4
#define SORT_PUNKBUSTER		5

// Legacy vmMain call order shared by QVMs and classic DLLs.
typedef enum {
	UI_GETAPIVERSION = 0,	// system reserved

	UI_INIT,
//	void	UI_Init( void );

	UI_SHUTDOWN,
//	void	UI_Shutdown( void );

	UI_KEY_EVENT,
//	void	UI_KeyEvent( int key );

	UI_MOUSE_EVENT,
//	void	UI_MouseEvent( int dx, int dy );

	UI_REFRESH,
//	void	UI_Refresh( int time );

	UI_IS_FULLSCREEN,
//	qboolean UI_IsFullscreen( void );

	UI_SET_ACTIVE_MENU,
//	void	UI_SetActiveMenu( uiMenuCommand_t menu );

	UI_CONSOLE_COMMAND,
//	qboolean UI_ConsoleCommand( int realTime );

	UI_DRAW_CONNECT_SCREEN,
//	void	UI_DrawConnectScreen( qboolean overlay );
	UI_HASUNIQUECDKEY,
	UI_REFRESH_DISPLAY_CONTEXT,
	UI_MENUS_ANY_VISIBLE,
	UI_FOR_EACH_ARENA_NAME,
	UI_DRAW_ADVERTISEMENT_WAIT_SCREEN
// if !overlay, the background will be drawn, otherwise it will be
// overlayed over whatever the cgame has drawn.
// a GetClientState syscall will be made to get the current strings
} uiExport_t;

// Retail Quake Live native DLL slot order recovered from uix86.dll dllEntry().
typedef enum {
	UI_NATIVE_EXPORT_INIT,
	UI_NATIVE_EXPORT_SHUTDOWN,
	UI_NATIVE_EXPORT_KEY_EVENT,
	UI_NATIVE_EXPORT_MOUSE_EVENT,
	UI_NATIVE_EXPORT_REFRESH,
	UI_NATIVE_EXPORT_IS_FULLSCREEN,
	UI_NATIVE_EXPORT_SET_ACTIVE_MENU,
	UI_NATIVE_EXPORT_CONSOLE_COMMAND,
	UI_NATIVE_EXPORT_DRAW_CONNECT_SCREEN,
	UI_NATIVE_EXPORT_HAS_UNIQUE_CD_KEY,
	UI_NATIVE_EXPORT_REFRESH_DISPLAY_CONTEXT,
	UI_NATIVE_EXPORT_MENUS_ANY_VISIBLE,
	UI_NATIVE_EXPORT_FOR_EACH_ARENA_NAME,
	UI_NATIVE_EXPORT_DRAW_ADVERTISEMENT_WAIT_SCREEN,
	UI_NATIVE_EXPORT_COUNT
} uiNativeExport_t;

#endif
