# Export a full Ghidra C-language source recreation for the Quake Live UI module.
#@author QuakeLive-reverse
#@category QuakeLive/UI
#@menupath Tools.QuakeLive.Export UI Source Recreation
#@toolbar

"""Decompile every function in uix86.dll and write a structured C source recreation.

Run *after* ``ApplyUISymbolMap.py`` so that function names reflect the committed
symbol map before the C output is generated.

Output layout under ``<output_root>/ui/``::

    <output_root>/ui/
        ui_reconstruction.c   -- full annotated decompile, all functions
        include/
            ui_prototypes.h   -- forward declarations for all decompiled functions

Run via the Ghidra GUI or headless::

    analyzeHeadless <project_dir> <project_name> \
        -process uix86.dll \
        -postScript ExportUISourceRecreation.py \
        [<output_root>]

``<output_root>`` defaults to ``<repo_root>/src-re/ui``.  The script resolves
``<repo_root>`` relative to its own location (``<repo_root>/ghidra_scripts/``).
"""

import os

from ghidra.app.decompiler import DecompInterface
from ghidra.app.script import GhidraScript
from ghidra.program.model.listing import FunctionIterator


_HEADER = """\
/*
 * Quake Live UI Module — Ghidra C-language source recreation
 *
 * Binary  : uix86.dll
 * Source  : Ghidra decompiler output with committed symbol-map annotations
 *           applied via ghidra_scripts/ApplyUISymbolMap.py
 *
 * This file is machine-assisted output from the Ghidra decompiler.  It is
 * intended as a reverse-engineering reference, not a drop-in replacement.
 * Treat it as a hint set alongside the Binary Ninja HLIL dumps in
 *   references/hlil/quakelive/uix86.all/
 * and the companion Ghidra corpus in
 *   references/reverse-engineering/ghidra/uix86/
 *
 * Do NOT edit this file by hand — regenerate it by running:
 *   ApplyUISymbolMap.py  (rename pass)
 *   ExportUISourceRecreation.py  (export pass)
 */

#include "include/ui_prototypes.h"

"""

_PROTO_HEADER = """\
/*
 * Quake Live UI Module — function forward declarations
 *
 * Auto-generated by ghidra_scripts/ExportUISourceRecreation.py
 * Do NOT edit by hand — regenerate from Ghidra.
 */

#ifndef UI_PROTOTYPES_H
#define UI_PROTOTYPES_H

"""

_PROTO_FOOTER = "\n#endif /* UI_PROTOTYPES_H */\n"


class ExportUISourceRecreation(GhidraScript):

	# ------------------------------------------------------------------
	# Helpers
	# ------------------------------------------------------------------

	@staticmethod
	def _ensure_dir(path):
		if not os.path.isdir(path):
			os.makedirs(path)

	@staticmethod
	def _write(path, text):
		with open(path, "w") as fh:
			fh.write(text)

	# ------------------------------------------------------------------

	def run(self):
		program = self.currentProgram
		if program is None:
			self.printerr("No program is active; aborting")
			return

		script_dir = os.path.dirname(os.path.abspath(str(sourceFile)))
		repo_root = os.path.dirname(script_dir)
		default_out = os.path.join(repo_root, "src-re", "ui")

		args = list(self.getScriptArgs())
		output_root = args[0] if args else default_out

		recon_dir = output_root
		include_dir = os.path.join(output_root, "include")
		self._ensure_dir(recon_dir)
		self._ensure_dir(include_dir)

		func_manager = program.getFunctionManager()

		# Collect all non-external functions sorted by entry address for
		# deterministic output ordering.
		funcs = []
		func_iter = func_manager.getFunctions(True)
		while func_iter.hasNext():
			func = func_iter.next()
			if not func.isExternal():
				funcs.append(func)
		funcs.sort(key=lambda f: f.getEntryPoint().getOffset())

		self.println(
			"ExportUISourceRecreation: decompiling %d functions..." % len(funcs)
		)

		decompiler = DecompInterface()
		decompiler.openProgram(program)

		recon_lines = [_HEADER]
		proto_lines = [_PROTO_HEADER]
		succeeded = 0
		failed = 0

		for func in funcs:
			if self.monitor.isCancelled():
				break

			name = func.getName()
			addr = func.getEntryPoint()
			size = func.getBody().getNumAddresses()

			recon_lines.append(
				"/* %s @ %s  size %d */" % (name, addr, size)
			)

			results = decompiler.decompileFunction(func, 90, self.monitor)
			if results is None or not results.decompileCompleted() or results.getDecompiledFunction() is None:
				recon_lines.append("/* decompile failed */\n")
				failed += 1
				continue

			c_code = results.getDecompiledFunction().getC()
			recon_lines.append(c_code)
			recon_lines.append("")
			succeeded += 1

			# Collect a prototype for the header.
			proto = results.getDecompiledFunction().getSignature()
			if proto:
				proto_lines.append("%s;" % proto)

		decompiler.dispose()

		self._write(
			os.path.join(recon_dir, "ui_reconstruction.c"),
			"\n".join(recon_lines)
		)

		proto_lines.append(_PROTO_FOOTER)
		self._write(
			os.path.join(include_dir, "ui_prototypes.h"),
			"\n".join(proto_lines)
		)

		self.println(
			"ExportUISourceRecreation: succeeded=%d failed=%d -> %s"
			% (succeeded, failed, output_root)
		)


ExportUISourceRecreation().run()
